// Pinned subset of Valve's Steam authentication contract used by Sentinel.
// Keep field numbers synchronized with the tested HTTPS QR flow before changing.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: steam_auth.proto

package generator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAuthTokenPlatformType int32

const (
	EAuthTokenPlatformType_Unknown     EAuthTokenPlatformType = 0
	EAuthTokenPlatformType_SteamClient EAuthTokenPlatformType = 1
)

// Enum value maps for EAuthTokenPlatformType.
var (
	EAuthTokenPlatformType_name = map[int32]string{
		0: "Unknown",
		1: "SteamClient",
	}
	EAuthTokenPlatformType_value = map[string]int32{
		"Unknown":     0,
		"SteamClient": 1,
	}
)

func (x EAuthTokenPlatformType) Enum() *EAuthTokenPlatformType {
	p := new(EAuthTokenPlatformType)
	*p = x
	return p
}

func (x EAuthTokenPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAuthTokenPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_steam_auth_proto_enumTypes[0].Descriptor()
}

func (EAuthTokenPlatformType) Type() protoreflect.EnumType {
	return &file_steam_auth_proto_enumTypes[0]
}

func (x EAuthTokenPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAuthTokenPlatformType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAuthTokenPlatformType(num)
	return nil
}

// Deprecated: Use EAuthTokenPlatformType.Descriptor instead.
func (EAuthTokenPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{0}
}

type DeviceDetails struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	DeviceFriendlyName *string                 `protobuf:"bytes,1,opt,name=device_friendly_name,json=deviceFriendlyName" json:"device_friendly_name,omitempty"`
	PlatformType       *EAuthTokenPlatformType `protobuf:"varint,2,opt,name=platform_type,json=platformType,enum=sentinel.generator.steamauth.EAuthTokenPlatformType" json:"platform_type,omitempty"`
	OsType             *int32                  `protobuf:"varint,3,opt,name=os_type,json=osType" json:"os_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceDetails) Reset() {
	*x = DeviceDetails{}
	mi := &file_steam_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDetails) ProtoMessage() {}

func (x *DeviceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_steam_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDetails.ProtoReflect.Descriptor instead.
func (*DeviceDetails) Descriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceDetails) GetDeviceFriendlyName() string {
	if x != nil && x.DeviceFriendlyName != nil {
		return *x.DeviceFriendlyName
	}
	return ""
}

func (x *DeviceDetails) GetPlatformType() EAuthTokenPlatformType {
	if x != nil && x.PlatformType != nil {
		return *x.PlatformType
	}
	return EAuthTokenPlatformType_Unknown
}

func (x *DeviceDetails) GetOsType() int32 {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return 0
}

type BeginAuthSessionViaQRRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	DeviceFriendlyName *string                 `protobuf:"bytes,1,opt,name=device_friendly_name,json=deviceFriendlyName" json:"device_friendly_name,omitempty"`
	PlatformType       *EAuthTokenPlatformType `protobuf:"varint,2,opt,name=platform_type,json=platformType,enum=sentinel.generator.steamauth.EAuthTokenPlatformType" json:"platform_type,omitempty"`
	DeviceDetails      *DeviceDetails          `protobuf:"bytes,3,opt,name=device_details,json=deviceDetails" json:"device_details,omitempty"`
	WebsiteId          *string                 `protobuf:"bytes,4,opt,name=website_id,json=websiteId" json:"website_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BeginAuthSessionViaQRRequest) Reset() {
	*x = BeginAuthSessionViaQRRequest{}
	mi := &file_steam_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthSessionViaQRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthSessionViaQRRequest) ProtoMessage() {}

func (x *BeginAuthSessionViaQRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steam_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthSessionViaQRRequest.ProtoReflect.Descriptor instead.
func (*BeginAuthSessionViaQRRequest) Descriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{1}
}

func (x *BeginAuthSessionViaQRRequest) GetDeviceFriendlyName() string {
	if x != nil && x.DeviceFriendlyName != nil {
		return *x.DeviceFriendlyName
	}
	return ""
}

func (x *BeginAuthSessionViaQRRequest) GetPlatformType() EAuthTokenPlatformType {
	if x != nil && x.PlatformType != nil {
		return *x.PlatformType
	}
	return EAuthTokenPlatformType_Unknown
}

func (x *BeginAuthSessionViaQRRequest) GetDeviceDetails() *DeviceDetails {
	if x != nil {
		return x.DeviceDetails
	}
	return nil
}

func (x *BeginAuthSessionViaQRRequest) GetWebsiteId() string {
	if x != nil && x.WebsiteId != nil {
		return *x.WebsiteId
	}
	return ""
}

type BeginAuthSessionViaQRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *uint64                `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ChallengeUrl  *string                `protobuf:"bytes,2,opt,name=challenge_url,json=challengeUrl" json:"challenge_url,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Interval      *float32               `protobuf:"fixed32,4,opt,name=interval" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthSessionViaQRResponse) Reset() {
	*x = BeginAuthSessionViaQRResponse{}
	mi := &file_steam_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthSessionViaQRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthSessionViaQRResponse) ProtoMessage() {}

func (x *BeginAuthSessionViaQRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steam_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthSessionViaQRResponse.ProtoReflect.Descriptor instead.
func (*BeginAuthSessionViaQRResponse) Descriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{2}
}

func (x *BeginAuthSessionViaQRResponse) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *BeginAuthSessionViaQRResponse) GetChallengeUrl() string {
	if x != nil && x.ChallengeUrl != nil {
		return *x.ChallengeUrl
	}
	return ""
}

func (x *BeginAuthSessionViaQRResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *BeginAuthSessionViaQRResponse) GetInterval() float32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

type PollAuthSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *uint64                `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	TokenToRevoke *uint64                `protobuf:"fixed64,3,opt,name=token_to_revoke,json=tokenToRevoke" json:"token_to_revoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollAuthSessionStatusRequest) Reset() {
	*x = PollAuthSessionStatusRequest{}
	mi := &file_steam_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAuthSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAuthSessionStatusRequest) ProtoMessage() {}

func (x *PollAuthSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steam_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAuthSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*PollAuthSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PollAuthSessionStatusRequest) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *PollAuthSessionStatusRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *PollAuthSessionStatusRequest) GetTokenToRevoke() uint64 {
	if x != nil && x.TokenToRevoke != nil {
		return *x.TokenToRevoke
	}
	return 0
}

type PollAuthSessionStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NewClientId          *uint64                `protobuf:"varint,1,opt,name=new_client_id,json=newClientId" json:"new_client_id,omitempty"`
	NewChallengeUrl      *string                `protobuf:"bytes,2,opt,name=new_challenge_url,json=newChallengeUrl" json:"new_challenge_url,omitempty"`
	RefreshToken         *string                `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	AccessToken          *string                `protobuf:"bytes,4,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	HadRemoteInteraction *bool                  `protobuf:"varint,5,opt,name=had_remote_interaction,json=hadRemoteInteraction" json:"had_remote_interaction,omitempty"`
	AccountName          *string                `protobuf:"bytes,6,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PollAuthSessionStatusResponse) Reset() {
	*x = PollAuthSessionStatusResponse{}
	mi := &file_steam_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAuthSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAuthSessionStatusResponse) ProtoMessage() {}

func (x *PollAuthSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steam_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAuthSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*PollAuthSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_steam_auth_proto_rawDescGZIP(), []int{4}
}

func (x *PollAuthSessionStatusResponse) GetNewClientId() uint64 {
	if x != nil && x.NewClientId != nil {
		return *x.NewClientId
	}
	return 0
}

func (x *PollAuthSessionStatusResponse) GetNewChallengeUrl() string {
	if x != nil && x.NewChallengeUrl != nil {
		return *x.NewChallengeUrl
	}
	return ""
}

func (x *PollAuthSessionStatusResponse) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

func (x *PollAuthSessionStatusResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *PollAuthSessionStatusResponse) GetHadRemoteInteraction() bool {
	if x != nil && x.HadRemoteInteraction != nil {
		return *x.HadRemoteInteraction
	}
	return false
}

func (x *PollAuthSessionStatusResponse) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

var File_steam_auth_proto protoreflect.FileDescriptor

const file_steam_auth_proto_rawDesc = "" +
	"\n" +
	"\x10steam_auth.proto\x12\x1csentinel.generator.steamauth\"\xb5\x01\n" +
	"\rDeviceDetails\x120\n" +
	"\x14device_friendly_name\x18\x01 \x01(\tR\x12deviceFriendlyName\x12Y\n" +
	"\rplatform_type\x18\x02 \x01(\x0e24.sentinel.generator.steamauth.EAuthTokenPlatformTypeR\fplatformType\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\x05R\x06osType\"\x9e\x02\n" +
	"\x1cBeginAuthSessionViaQRRequest\x120\n" +
	"\x14device_friendly_name\x18\x01 \x01(\tR\x12deviceFriendlyName\x12Y\n" +
	"\rplatform_type\x18\x02 \x01(\x0e24.sentinel.generator.steamauth.EAuthTokenPlatformTypeR\fplatformType\x12R\n" +
	"\x0edevice_details\x18\x03 \x01(\v2+.sentinel.generator.steamauth.DeviceDetailsR\rdeviceDetails\x12\x1d\n" +
	"\n" +
	"website_id\x18\x04 \x01(\tR\twebsiteId\"\x9c\x01\n" +
	"\x1dBeginAuthSessionViaQRResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12#\n" +
	"\rchallenge_url\x18\x02 \x01(\tR\fchallengeUrl\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x02R\binterval\"\x82\x01\n" +
	"\x1cPollAuthSessionStatusRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\fR\trequestId\x12&\n" +
	"\x0ftoken_to_revoke\x18\x03 \x01(\x06R\rtokenToRevoke\"\x90\x02\n" +
	"\x1dPollAuthSessionStatusResponse\x12\"\n" +
	"\rnew_client_id\x18\x01 \x01(\x04R\vnewClientId\x12*\n" +
	"\x11new_challenge_url\x18\x02 \x01(\tR\x0fnewChallengeUrl\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x124\n" +
	"\x16had_remote_interaction\x18\x05 \x01(\bR\x14hadRemoteInteraction\x12!\n" +
	"\faccount_name\x18\x06 \x01(\tR\vaccountName*6\n" +
	"\x16EAuthTokenPlatformType\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vSteamClient\x10\x01B&Z$sentinel/backend/generator;generator"

var (
	file_steam_auth_proto_rawDescOnce sync.Once
	file_steam_auth_proto_rawDescData []byte
)

func file_steam_auth_proto_rawDescGZIP() []byte {
	file_steam_auth_proto_rawDescOnce.Do(func() {
		file_steam_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steam_auth_proto_rawDesc), len(file_steam_auth_proto_rawDesc)))
	})
	return file_steam_auth_proto_rawDescData
}

var file_steam_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steam_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_steam_auth_proto_goTypes = []any{
	(EAuthTokenPlatformType)(0),           // 0: sentinel.generator.steamauth.EAuthTokenPlatformType
	(*DeviceDetails)(nil),                 // 1: sentinel.generator.steamauth.DeviceDetails
	(*BeginAuthSessionViaQRRequest)(nil),  // 2: sentinel.generator.steamauth.BeginAuthSessionViaQRRequest
	(*BeginAuthSessionViaQRResponse)(nil), // 3: sentinel.generator.steamauth.BeginAuthSessionViaQRResponse
	(*PollAuthSessionStatusRequest)(nil),  // 4: sentinel.generator.steamauth.PollAuthSessionStatusRequest
	(*PollAuthSessionStatusResponse)(nil), // 5: sentinel.generator.steamauth.PollAuthSessionStatusResponse
}
var file_steam_auth_proto_depIdxs = []int32{
	0, // 0: sentinel.generator.steamauth.DeviceDetails.platform_type:type_name -> sentinel.generator.steamauth.EAuthTokenPlatformType
	0, // 1: sentinel.generator.steamauth.BeginAuthSessionViaQRRequest.platform_type:type_name -> sentinel.generator.steamauth.EAuthTokenPlatformType
	1, // 2: sentinel.generator.steamauth.BeginAuthSessionViaQRRequest.device_details:type_name -> sentinel.generator.steamauth.DeviceDetails
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_steam_auth_proto_init() }
func file_steam_auth_proto_init() {
	if File_steam_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steam_auth_proto_rawDesc), len(file_steam_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steam_auth_proto_goTypes,
		DependencyIndexes: file_steam_auth_proto_depIdxs,
		EnumInfos:         file_steam_auth_proto_enumTypes,
		MessageInfos:      file_steam_auth_proto_msgTypes,
	}.Build()
	File_steam_auth_proto = out.File
	file_steam_auth_proto_goTypes = nil
	file_steam_auth_proto_depIdxs = nil
}
