// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function AddEmulator(arg1:string):Promise<void>;

export function LoadConfig():Promise<config.CfgFile>;

export function RemoveEmulator(arg1:number):Promise<void>;

export function SaveConfig():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ToggleEmulatorNotification(arg1:number):Promise<void>;
