// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEmulator(arg1) {
  return window['go']['config']['CfgFile']['AddEmulator'](arg1);
}

export function LoadConfig() {
  return window['go']['config']['CfgFile']['LoadConfig']();
}

export function RemoveEmulator(arg1) {
  return window['go']['config']['CfgFile']['RemoveEmulator'](arg1);
}

export function SaveConfig() {
  return window['go']['config']['CfgFile']['SaveConfig']();
}

export function SelectDirectory() {
  return window['go']['config']['CfgFile']['SelectDirectory']();
}

export function SetContext(arg1) {
  return window['go']['config']['CfgFile']['SetContext'](arg1);
}

export function ToggleEmulatorNotification(arg1) {
  return window['go']['config']['CfgFile']['ToggleEmulatorNotification'](arg1);
}
